[package]
name = "farc3"
description = "ARC3 solving for Constraint Satisfaction Problems"
readme = ".github/README.md"
version = "0.1.0"
edition = "2024"

[profile.dev]
incremental = true

[dependencies]
